version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Port pour S3
      - "4572:4572"  # Autres services AWS
    environment:
      - SERVICES=s3  # On active seulement S3
      - DOCKER_HOST=unix:///var/run/docker.sock
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Port MongoDB
